import Head from "next/head";
import HeaderOne from "@/components/HeaderOne";

export default function Home() {
  return (
    <>
      <Head>
        <title>Supportifly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderOne />
      </main>
    </>
  );
}
